#!/bin/bash
# Demo script for Notion MCP Server
# This shows how the MCP server would be used with Claude Code or other MCP clients

echo "=== Notion MCP Server Demo ==="
echo ""
echo "The MCP server provides 4 tools:"
echo ""
echo "1. notion_search - Search across your Notion workspace"
echo "   Example: Search for 'quarterly roadmap'"
echo ""
echo "2. notion_get_page - Retrieve page content"
echo "   Example: Get page by ID 'abc123-def456-ghi789'"
echo ""
echo "3. notion_create_page - Create new pages"
echo "   Example: Create a page titled 'Meeting Notes' under parent page"
echo ""
echo "4. notion_query_database - Query databases"
echo "   Example: Get all items from tasks database"
echo ""
echo "=== Setup Instructions ==="
echo ""
echo "1. Get your Notion integration token:"
echo "   https://www.notion.so/my-integrations"
echo ""
echo "2. Export the token:"
echo "   export NOTION_TOKEN='secret_xxx'"
echo ""
echo "3. Run the server:"
echo "   node dist/index.js"
echo ""
echo "4. Configure your MCP client (Claude Code, etc.) to use:"
echo "   ~/.openclaw/workspace/mcp-server-notion/dist/index.js"
echo ""
echo "=== Example Conversation ==="
echo ""
echo "User: 'Find my notes about the product launch'"
echo "AI → notion_search: {query: 'product launch'}"
echo "AI → notion_get_page: {page_id: 'found-page-id'}"
echo "AI → 'Here are your product launch notes...'"
echo ""
